language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.0
  - 2.1
  - jruby-9.0.1.0

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.0.5.gemfile
  - gemfiles/rails_4.0_with_therubyracer.gemfile
  - gemfiles/rails_4.2_sprockets_2.gemfile
  - gemfiles/rails_4.2_sprockets_3.gemfile
  - gemfiles/rails_4.2_sprockets_4.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_5_no_sprockets.gemfile
  - gemfiles/rails_5_sprockets_4.gemfile

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.1
      gemfile: rails_4.0_with_therubyracer.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_4.2_sprockets_2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_4.2_sprockets_4.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5_no_sprockets.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5_sprockets_4.gemfile
    - rvm: jruby-9.0.1.0
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: jruby-9.0.1.0
      gemfile: rails_4.0_with_therubyracer.gemfile
    - rvm: jruby-9.0.1.0
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: jruby-9.0.1.0
      gemfile: gemfiles/rails_4.2_sprockets_2.gemfile

  allow_failures:
    - rvm: jruby-9.0.1.0

before_install:
  - mkdir travis-phantomjs
  - wget https://rmosolgo.github.io/assets/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs --version
