language: ruby
sudo: required
dist: trusty
addons:
  chrome: stable
cache:
  bundler: true
  yarn: true
rvm:
  - 2.7.0
  - 2.6.4
  - 2.5.7
  - jruby-9.1.9.0

gemfile:
  # These have webpacker:
  - gemfiles/rails_5.2_no_sprockets.gemfile
  - gemfiles/rails_5.2_no_sprockets_webpacker_3.gemfile
  - gemfiles/rails_5.2_no_sprockets_webpacker_4.gemfile
  # These don't have webpacker:
  - gemfiles/rails_5.2_sprockets_3.gemfile
  - gemfiles/rails_5.2_sprockets_4.gemfile

matrix:
  fast_finish: true
  exclude:
    # Oldest rails does not run on ruby 2.6
    - rvm: 2.6.2
      gemfile: gemfiles/rails_4.2_sprockets_4.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_4.2_sprockets_3.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_4.2_sprockets_2.gemfile
    - rvm: 2.5.3
    - rvm: 2.3.8
    - rvm: jruby-9.1.9.0

  include:
    # Oldest rails does not run on ruby 2.6
    - rvm: 2.5.3
      gemfile: gemfiles/rails_4.2_sprockets_4.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_4.2_sprockets_3.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_4.2_sprockets_2.gemfile
    # Newest gemfiles for universal testing
    - rvm: 2.5.3
      gemfile: gemfiles/rails_5.2_no_sprockets_webpacker_4.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_5.2_sprockets_4.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_5.2_no_sprockets_webpacker_4.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_5.2_sprockets_4.gemfile
    - rvm: jruby-9.1.9.0
      gemfile: gemfiles/rails_5.2_no_sprockets_webpacker_4.gemfile
    - rvm: jruby-9.1.9.0
      gemfile: gemfiles/rails_5.2_sprockets_4.gemfile

  allow_failures:
    - rvm: jruby-9.1.9.0
      gemfile: gemfiles/rails_5.2_no_sprockets_webpacker_4.gemfile
    - rvm: jruby-9.1.9.0
      gemfile: gemfiles/rails_5.2_sprockets_4.gemfile

before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - gem update --system
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
