# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on: [push]
jobs:
  check_react_and_ujs:
    strategy:
      fail-fast: true
      matrix:
        ruby: [2.7]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler: 2.4.9
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/setup-node@v3
      - run: bundle install
      - run: yarn
      - run: bundle exec rake react:update
      - run: bundle exec rake ujs:update
      - run: ./check_for_uncommitted_files.sh

  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7]
        gemfile:
          # These have webpacker:
          - rails_5.2_no_sprockets
          - rails_5.2_no_sprockets_webpacker_3
          - rails_5.2_no_sprockets_webpacker_4
          # These don't have webpacker:
          - rails_5.2_sprockets_3
          - rails_5.2_sprockets_4
    runs-on: ubuntu-latest
    env:
      # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      # Workaround b/c upgrading Minitest broke some mocking expectations
      # having to do with automatic kwarg splatting
      MT_KWARGS_HACK: 1
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler: 2.4.9
        ruby-version: ${{ matrix.ruby }}
        # TODO: Impalement caching
        # bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test
      env:
        NODE_OPTIONS: --openssl-legacy-provider
